# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1rZksQGkpVbk2UO5FdX2WPyInWXTdlo
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/
# !ls
#
# !git clone https://github.com/4rtur1t0/TrashYolo
#
# # Commented out IPython magic to ensure Python compatibility.
# # %cd TrashYolo
# !ls
#
# !wget https://arvc.umh.es/arte/datasets.zip
#
# !unzip datasets.zip
#
# pip install ultralytics
#
# pip install tqdm
#
# from ultralytics import YOLO
# model = YOLO('yolov8n.pt')  # smallest model (fast)
# model.train(data='trash_taco.yaml', epochs=20, imgsz=640)